groups:
  - name: CheckAvailability
    rules:
      - alert: ConsumerAvailability
        expr: (rabbitmq_queue_consumer_utilisation*100) < 100
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Consumer struggling (instance {{ $labels.instance }})"
          description: "Consumer availability (< 100%)\n  VALUE = {{ $value }}%\n  LABELS: {{ $labels }}"