global:
  scrape_interval: 15s
  external_labels:
      monitor: 'rabbitmq-monitor'

rule_files:
  - 'alerts/unacked_msg.yml'
  - 'alerts/no_consumers.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9090']