global:
  scrape_interval: 15s
  external_labels:
      monitor: 'rabbitmq-monitor'

rule_files:
  - 'alerts/cons_availability.yml'
  - 'alerts/unacked_msg.yml'
  - 'alerts/no_consumers.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9090']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: 
          - 'alertmanager:9093'
