{
 "title": "RabbitMQ Metrics",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Server",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rabbitmq_up" }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\",job=\"prometheus\"}",
     "legendFormat": "prometheus on {{instance}}"
    },
    {
     "expr": "up{instance=\"localhost:15672\",job=\"rabbitmq_exporter\"}",
     "legendFormat": "rabbitmq on {{instance}}"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_exchanges", "legendFormat": "exchanges on {{instance}}" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "channels on {{instance}}" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "consumers on {{instance}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "connections on {{instance}}" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "queues on {{instance}}" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "queues on {{instance}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues_disk_reads", "legendFormat": "{{queue}}:disk reads" },
    { "expr": "rabbitmq_queues_disk_writes", "legendFormat": "{{queue}}:disk writes" }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}:{{durable}}" }
   ]
  },
  {
   "title": "Consumer Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation*100",
     "legendFormat": "consumer on {{queue}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"ConsumerAvailability\"}",
     "legendFormat": "{{alertname}}:{{alertstate}}-{{severity}}-{{queue}}"
    }
   ]
  },
  {
   "title": "Messages/host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready)",
     "legendFormat": "ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "unack"
    }
   ]
  }
 ]
}