{
 "title": "RabbitMQ + MongoDB Metrics",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Health",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rabbitmq_node_up" }
   ]
  },
  {
   "title": "MongoDB Health",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mongodb_up" }
   ]
  },
  {
   "title": "Prometheus Health",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\",job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Services Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\",job=\"prometheus\"}",
     "legendFormat": "prometheus on {{instance}}"
    },
    {
     "expr": "up{instance=\"localhost:15672\",job=\"rabbitmq\"}",
     "legendFormat": "rabbitmq on {{instance}}"
    },
    { "expr": "mongodb_up", "legendFormat": "mongodb on {{instance}}" }
   ]
  },
  {
   "title": "Prometheus Alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "{{alertname}}:{{alertstate}}-{{severity}}-{{queue}}"
    },
    {
     "expr": "ALERTS{alertstate=\"pending\"}",
     "legendFormat": "{{alertname}}:{{alertstate}}-{{severity}}-{{queue}}"
    }
   ]
  },
  { "title": "Grafana Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_exchanges", "legendFormat": "exchanges on {{instance}}" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "no. of queues on {{instance}}" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "channels on {{instance}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "connections on {{instance}}" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "consumers on {{instance}}" }
   ]
  },
  {
   "title": "Consumer Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "{{ queue }}"
    },
    {
     "expr": "rabbitmq_queue_consumer_utilisation{queue=\"MongoImageQueue\"}",
     "legendFormat": "{{ queue }}"
    },
    {
     "expr": "rabbitmq_queue_consumer_utilisation{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Dicom DB Number of Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_db_objects_total{db=\"dicom\",instance=\"localhost:9001\",job=\"mongodb\"}",
     "legendFormat": "mongodb database: {{db}}"
    }
   ]
  },
  {
   "title": "AccessionDirectoryQueue Messages",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "published"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "delivered"
    },
    {
     "expr": "rabbitmq_queue_messages_confirmed_total{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "confirmed"
    },
    {
     "expr": "rabbitmq_queue_messages_unacknowledged{queue=\"AccessionDirectoryQueue\"}",
     "legendFormat": "unacknowledged"
    }
   ]
  },
  {
   "title": "MongoImageQueue Messages",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total{queue=\"MongoImageQueue\"}",
     "legendFormat": "published"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"MongoImageQueue\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"MongoImageQueue\"}",
     "legendFormat": "delivered"
    },
    {
     "expr": "rabbitmq_queue_messages_confirmed_total{queue=\"MongoImageQueue\"}",
     "legendFormat": "confirmed"
    },
    {
     "expr": "rabbitmq_queue_messages_unacknowledged{queue=\"MongoImageQueue\"}",
     "legendFormat": "unacknowledged"
    }
   ]
  },
  {
   "title": "MongoSeriesQueue Messages",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "published"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "delivered"
    },
    {
     "expr": "rabbitmq_queue_messages_confirmed_total{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "confirmed"
    },
    {
     "expr": "rabbitmq_queue_messages_unacknowledged{queue=\"MongoSeriesQueue\"}",
     "legendFormat": "unacknowledged"
    }
   ]
  },
  {
   "title": "RabbitMQ Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues_disk_reads", "legendFormat": "rabbitmq disk reads" },
    { "expr": "rabbitmq_queues_disk_writes", "legendFormat": "rabbitmq disk writes" },
    { "expr": "rabbitmq_core_node_mem_limit", "legendFormat": "rabbitmq memory limit" },
    { "expr": "rabbitmq_core_node_mem_used", "legendFormat": "rabbitmq memory used" }
   ]
  },
  {
   "title": "MongoDB Memory Utilisation ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "mongodb_db_data_size_bytes{instance=\"localhost:9001\",job=\"mongodb\"}",
     "legendFormat": "database: {{db}}"
    }
   ]
  },
  {
   "title": "RabbitMQ Messages",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready)",
     "legendFormat": "ready on {{vhost}}"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "published on {{vhost}}"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "delivered on {{vhost}}"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "unack on {{vhost}}"
    }
   ]
  },
  {
   "title": "MongoDB Operations",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}