groups:
  - name: CheckUnacked
    rules:
      - alert: ConsumerStruggling
        expr: rabbitmq_queue_messages_unacknowledged_total > 500
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Too many unacknowledged messages in queue (instance {{ $labels.instance }})"
          description: "Queue is filling up (> 1000 msgs)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"